Pid refactoring
o3de/o3de-extras pull request #175
Opened 2023-02-16 09:52 UTC by danielemorra98

I moved the location of `PIDConfiguration.*` from `VehicleDynamics/DriveModels` to `Utilities/Controllers` so that it could be reused by other components without referring to VehicleDynamics dependency.

2023-02-16 13:53 UTC, adamdbrw commented
@danielemorra98 could you please cast this against development and only keep the actual change in the PR?

2023-02-16 14:46 UTC, michalpelka commented on Gems/ROS2/Code/Source/Lidar/LidarRaycaster.h
> +#include <ROS2/Lidar/LidarRaycasterBus.h>
Why this file is touched by this PR?

2023-02-16 14:46 UTC, michalpelka commented on Gems/XR/Code/Include/XR/XRSystem.h
> +        AZ::Data::Instance<AZ::RPI::AttachmentImage> InitPassFoveatedAttachment(const AZ::RPI::PassTemplate& passTemplate, const AZ::RHI::XRFoveatedLevel* level = nullptr) const override;
Why this file is touched by the PR at all?

2023-02-16 14:49 UTC, michalpelka requested changes
I think PR is containing changes that are added by mistake.
Please adjust the contribution to the intended changes.

2023-02-17 11:42 UTC, hultonha commented
@danielemorra98 Did you see @michalpelka's comment? Can any accidentally added files be removed from this PR please? Thanks!

2023-02-20 09:06 UTC, closed without merging