Refactor ROS 2 System components
o3de/o3de-extras pull request #628
Opened 2023-12-04 17:51 UTC by michalpelka

Fixes #626

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/SystemComponents/ROS2CameraSystemComponent.cpp
> +/*
Directory "SystemComponents" could be misleading, as it has only some of system components, but not all of them.
Perhaps the new camera SC should go to the Camera folder instead (much like it is with lidar)?

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/SystemComponents/ROS2CameraSystemComponent.cpp
> +
```suggestion
```

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/SystemComponents/ROS2CameraSystemComponent.cpp
> +   void ROS2SystemCameraComponent::Init()
Empty functions can be removed

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/SystemComponents/ROS2CameraSystemComponent.cpp
> +               ec->Class<ROS2SystemCameraComponent>("ROS2 System Camera Component", "This system component is responsible for the ROS2 Camera simulation.")
```suggestion
               ec->Class<ROS2SystemCameraComponent>("ROS 2 System Camera Component", "This system component is responsible for setting a pass template for simulation of camera sensors.")
```

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/SystemComponents/ROS2CameraSystemComponent.cpp
> +
```suggestion
```

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
> +        AZ_Assert(ros2Node, "ROS2 node is not initialized");
```suggestion
        AZ_Assert(ros2Node, "ROS 2 node is not initialized");
```

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/Spawner/ROS2SpawnerComponent.cpp
> +        AZ_Assert(ros2Node, "ROS2 node is not initialized");
This should be for the whole codebase.

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/SystemComponents/ROS2CameraSystemEditorComponent.cpp
> +
```suggestion
```

2023-12-06 10:56 UTC, adamdbrw commented on Gems/ROS2/Code/Source/SystemComponents/ROS2CameraSystemEditorComponent.h
> +    /// System component for ROS2 editor
Update documentation

2023-12-07 10:14 UTC, michalpelka commented
The services that are provided in system components are not global, they are available only in System Entity.

2023-12-11 13:54 UTC, jhanca-robotecai requested changes
The code builds and runs correctly.

Please fix the duplicated header reference in cmake file. The remaining comments can be considered nitpicks.

2023-12-11 14:37 UTC, michalpelka commented on Gems/ROS2/Code/Source/Camera/ROS2CameraSystemEditorComponent.h
Renamed ROS2EditorCameraSystemComponent.

2023-12-11 15:09 UTC, michalpelka commented
@jhanca-robotecai updated my contribution.

2023-12-11 15:20 UTC, michalpelka commented on Gems/ROS2/Code/Source/Camera/ROS2CameraSystemComponent.h
> +       ~ROS2SystemCameraComponent() override = default;
Technically, we override the virtual destructor in  AZ::Component.

2023-12-11 15:46 UTC, jhanca-robotecai approved these changes
All my remarks were taken into consideration, no more issues from my side.

2023-12-14 12:53 UTC, merged