Migration of demo project to o3de-extras
o3de/o3de-extras pull request #77
Opened 2022-12-12 15:18 UTC by michalpelka

This PR is a migration of the main branch of the [repository](https://github.com/RobotecAI/o3de-demo-project).
It contains ROS2 navigation demo utilizing this [sample scene](https://github.com/o3de/loft-arch-vis-sample).

2022-12-12 17:43 UTC, lumberyard-employee-dm commented on Projects/ROS2NavigationExample/Assets/Importer/Examples/turtlebot4/irobot_create_description/LICENSE
> +IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBS
So what is the actually category of license for the turtlebot4?

2022-12-12 17:53 UTC, lumberyard-employee-dm requested changes

2022-12-12 17:53 UTC, lumberyard-employee-dm commented on Projects/ROS2NavigationExample/Registry/bootstrap.setreg
> +
This file should be deleted.
Setting the `project_path` should not be done in the shared settings

2022-12-17 02:04 UTC, spham-amzn commented
Can you close this PR in favor of https://github.com/o3de/RobotVacuumSample/pull/1 ?

2022-12-19 09:24 UTC, michalpelka commented
Closing in favor of other [pr](https://github.com/o3de/RobotVacuumSample/pull/1).

2022-12-19 09:25 UTC, michalpelka commented
Closing in favor of https://github.com/o3de/RobotVacuumSample/pull/1.

2022-12-19 09:25 UTC, closed without merging